### ISSUE TITLE
Case sensitive file name

### ISSUE THREAD

**Issue by ip512** [michael-schaefer-eu/wkhtmltox#1]
Hi,
I'm trying to use the class Wkhtmltopdf on linux, with php 7.3, and I have a error `Uncaught Error: Class 'Wkhtmltox\Wkhtmltopdf' not found`.
If I rename the class file with an uppercase W, it fix the issue. Is it possible to rename the class file ? 
Thank you

**Comment by michael-schaefer-eu** [comment]
@ip512 Thanks for the hint, I corrected it.

**Comment by ip512** [comment]
Thank you :+1:
